paths:
  tests: tests
  output: artifacts
  data: tests/_data
  support: tests/_support
  envs: tests/_envs
actor_suffix: Tester
settings:
  shuffle: true
extensions:
  enabled:
    - Codeception\Extension\RunFailed
modules:
  enabled:
    - Codeception\Module\Asserts
    - StanfordCaravan\Codeception\Drupal\DrupalBootstrap:
        root: '/var/www/html/docroot'
        server:
          HTTP_HOST: 'localhost'
    - StanfordCaravan\Codeception\Drupal\DrupalDrush:
        drush: '/var/www/html/vendor/bin/drush'
        options:
          uri: 'localhost'
    - PhpBrowser:
        url: 'http://localhost/'
    - WebDriver:
        debug_log_entries: 10
        browser: chrome
        url: 'http://localhost/'
    - StanfordCaravan\Codeception\Drupal\DrupalEntity:
        cleanup_test: true
        cleanup_failed: false
        cleanup_suite: true
        route_entities:
          - node
          - taxonomy_term
          - media
    - StanfordCaravan\Codeception\Drupal\DrupalUser:
        drush: '/var/www/html/vendor/bin/drush'
        default_role: 'authenticated'
        driver: 'WebDriver'
        cleanup_entities:
          - node
          - media
          - file
        cleanup_test: true
        cleanup_failed: false
        cleanup_suite: true
