paths:
    tests: codeception
    output: ../artifacts
    data: ../artifacts/_data
    support: codeception/_support
    envs: codeception/_envs
actor_suffix: Tester
extensions:
    enabled:
        - Codeception\Extension\RunFailed
