# Codeception Test Suite Configuration
#
# Suite for functional tests
# Emulate web requests and make application process them
# Include one of framework modules (Symfony2, Yii2, Laravel5, Phalcon4) to use it
# Remove this suite if you don't use frameworks

actor: FunctionalTester
modules:
  enabled:
    # add a framework module here
    - \Helper\Functional
    - Codeception\Module\Asserts
    - StanfordCaravan\Codeception\Drupal\DrupalBootstrap:
        root: '/var/www/html/docroot'
        server:
          HTTP_HOST: 'localhost'
    - StanfordCaravan\Codeception\Drupal\DrupalDrush:
        drush: '/var/www/html/vendor/bin/drush'
        options:
          uri: 'localhost'
    - WebBrowser:
        url: 'http://localhost'
    - StanfordCaravan\Codeception\Drupal\DrupalEntity:
        cleanup_test: true
        cleanup_failed: false
        cleanup_suite: true
        route_entities:
          - node
          - taxonomy_term
          - media
    - StanfordCaravan\Codeception\Drupal\DrupalUser:
        drush: '/var/www/html/vendor/bin/drush'
        default_role: 'authenticated'
        driver: 'WebBrowser'
        cleanup_entities:
          - node
          - media
          - file
        cleanup_test: true
        cleanup_failed: false
        cleanup_suite: true
  step_decorators: ~
